// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBavo2-ticpcGRIE8ITx3HVo2tFl26yTC4',
    appId: '1:1037611065518:web:b77aedbde7caadc5170d3f',
    messagingSenderId: '1037611065518',
    projectId: 'firstfire-ed885',
    authDomain: 'firstfire-ed885.firebaseapp.com',
    storageBucket: 'firstfire-ed885.appspot.com',
    measurementId: 'G-HL5JHF3LNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBomcx8G5wiPrATXdTbq30gN_qHovVlR7U',
    appId: '1:1037611065518:android:7de612e8e69c58e4170d3f',
    messagingSenderId: '1037611065518',
    projectId: 'firstfire-ed885',
    storageBucket: 'firstfire-ed885.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGbvtDTC_JMh-iRaZ9Xkq-5CEDelT4kfM',
    appId: '1:1037611065518:ios:17f20b2ca442127a170d3f',
    messagingSenderId: '1037611065518',
    projectId: 'firstfire-ed885',
    storageBucket: 'firstfire-ed885.appspot.com',
    iosClientId: '1037611065518-qh5q4u6i2tn4gqq2bnlrvn8hd9q6mb80.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGbvtDTC_JMh-iRaZ9Xkq-5CEDelT4kfM',
    appId: '1:1037611065518:ios:17f20b2ca442127a170d3f',
    messagingSenderId: '1037611065518',
    projectId: 'firstfire-ed885',
    storageBucket: 'firstfire-ed885.appspot.com',
    iosClientId: '1037611065518-qh5q4u6i2tn4gqq2bnlrvn8hd9q6mb80.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopApp',
  );
}
